### ISSUE TITLE
Add Memo, Mutable

### ISSUE THREAD

**Issue by fredpi** [Flinesoft/HandySwift#16]
I suggest adding the `Memo` Type to HandySwift, based on [this repo](https://github.com/robrix/Memo/tree/326153487940ab19c1d25761656269e25fbbf119).

My suggested implementation adjusting the implementation a bit can be found [here](https://gist.github.com/fredpi/14609c2a9411af5eb071fa35ae3c5a90).

**Comment by Dschee** [comment]
Could you please explain, how this would improve Swift with some usage examples and why you think "it should have been part of the Swift Standard Library"? Also, could you check if there were discussions about this (or something solving the same problem) at the new [Swift Evolution Forum](https://forums.swift.org/c/evolution) and link it here, if you can find it? Thank you in advance.

**Comment by fredpi** [comment]
As pointed out in #17, wrapper types aren't very _swifty_, in that they should be a part of the standard library. While `Mutable` would be needed for some rare use cases (as seen in the `Memo` implementation), its use shouldn't be encouraged by being a part of Swift itself.

Same goes for `Memo`, which, in fact, is just a lazy box somehow. So while useful, they both don't fit here. Closing...
