### ISSUE TITLE
Add Weak

### ISSUE THREAD

**Issue by fredpi** [Flinesoft/HandySwift#17]
I suggest adding a `Weak` wrapper alongside the `Mutable` wrapper requested [here](https://github.com/Flinesoft/HandySwift/issues/16).

Suggested Implementation can be found [here](https://github.com/fredpi/SwiftCollections/blob/stable/Helpers/Weak.swift).

**Comment by Dschee** [comment]
Could you please explain, how this would improve Swift with some usage examples and why you think "it should have been part of the Swift Standard Library"? Also, could you check if there were discussions about this (or something solving the same problem) at the new [Swift Evolution Forum](https://forums.swift.org/c/evolution) and link it here, if you can find it? Thank you in advance.

**Comment by fredpi** [comment]
In fact there is a [discussion on this matter](https://forums.swift.org/t/pitch-rework-the-weak-keyword-into-a-weak-t-type-compiler-intrinsic/7749/14).

While some argue `Weak` is often useful in many projects, general consent seems to be it doesn't fit into the standard library, as the _"weak reference status"_ of a property should be a property of this property instead of a new type somehow...

This makes sense, and since I'd be against adding it to the standard library, it doesn't fit here either. Closing...
