### ISSUE TITLE
Xcode 10 complains about String extensions

### ISSUE THREAD

**Issue by dkalinai** [Flinesoft/HandySwift#22]
Seems like Xcode 10 with newer swift version complains about the following code: 

public enum AllowedCharacters {
        case numeric
        case alphabetic
        case alphaNumeric
        case allCharactersIn(String).   // Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'allCharactersIn(_:)' (identifier_name)
    }

resulting in not working:

   case .allCharactersIn(let allowedCharactersString):
                return allowedCharactersString
            }
        }()

**Comment by Dschee** [comment]
I'll have a look very soon and make a branch named `xcode-10` which you will be able to use. Stay tuned.

**Comment by dkalinai** [comment]
Sure thing, let me know how I can help you in testing. Etc.

**Comment by Dschee** [comment]
Okay, I have just tried building the project and saw the same issue. But this is actually a SwiftLint related one and SwiftLint doesn't even run when this project is included via Carthage. How are you including it? Via CocoaPods without frameworks? Or manually somehow?

**Comment by dkalinai** [comment]
I am trying to build it manually. The CSVImporter that uses HandySwift complains that HandySwift is not built with latest swift code. Thus taking me back to HandySwift project and when building manually i encounter this error. however I have realised that my problem came from not running the workspace and a single project, now it works fine. :)

**Comment by Dschee** [comment]
Please be aware that "not built with the latest swift code" usually can be solved by changing your toolchain to that of Xcode 10 and then, well, rebuilding your dependencies. But if you worked it out somehow differently, that's good, too. Btw this is a false positive on SwiftLint, so I [reported it there](https://github.com/realm/SwiftLint/issues/2231). Closing this one then. I'll probably still do a Xcode 10 branch soon to elaborate what we should change.

**Comment by mthole** [comment]
If anyone else is still running into this after upgrading to 0.27, try deleting your `Pods/SwiftLint` directory and reinstalling via `pod install`. That fixed the issue for me.
