### ISSUE TITLE
Unowned issue

### ISSUE THREAD

**Issue by dyrkabes** [Flinesoft/HandySwift#24]
Hello there!

There's some error in the library's playground in those lines (317-321):

````
//: ## Unowned
//: `Unowned` is a wrapper to store unowned references to a `Wrapped` instance.
//: ### Unowned(_:)
//: Initialize with an object reference.
var unowned = Unowned(text)  // error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x60400003f4).
The process has been left at the point where it was interrupted, use "thread return -x" to return to the state before expression evaluation.
````

I've checked,  the `text` variable is still available.

I also copied the unowned file to my project and tested. Still got an error but in another place:

````
        let text = NSString(string: "Hello!")
        let unowned = Unowned(text)
        print(unowned.value)  // "Hello!"
        print(unowned)  // Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
````

Not sure about the nature of this.

**Comment by Dschee** [comment]
Thank you for reporting this, I just checked and you're right, there an error. But I couldn't get behind this on first glance, either. Very weird one indeed...

**Comment by fredpi** [comment]
I could also reproduce this issue and it seems to be a persistent Xcode playground issue. Should we just comment out the lines that cause the playground not to work properly?

**Comment by Dschee** [comment]
@fredpi Makes sense. Let's do it like that. I'm sure you'd love to post the related PR? :)

**Comment by fredpi** [comment]
@Dschee Of course ;)
