### ISSUE TITLE
Carthage update failed with Xcode 8 / Swift 2.3

### ISSUE THREAD

**Issue by dunqi** [Flinesoft/HandySwift#3]
The following build commands failed:
	CompileSwift normal arm64 /Checkouts/HandySwift/Sources/Structs/FrequencyTable.swift
	CompileSwift normal arm64 /Checkouts/HandySwift/Sources/Globals.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(3 failures)

**Comment by Dschee** [comment]
@dunqi Feel free to fork the project, fix the issue and submit a pull request. ;)

**Comment by dunqi** [comment]
No idea what I'm doing - but feel free to check the pull request.
I Just startet Xcode and clicked the "convert to 2.3" button.

**Comment by Dschee** [comment]
Hey @dunqi – I released version 1.3.0 recently which makes HandySwift compatible with Xcode 8 by using Swift 3. As Carthage is building HandySwift directly it should not be necessary to update BartyCrouch to Swift 2.3 in addition to Swift 3 – please try v1.3.0 and report if it doesn't suit your needs. I'm closing this so long as you don't report any issues.
