### ISSUE TITLE
Add Comparable.bounded(lower:upper:) interface

### ISSUE THREAD

**Issue by fredpi** [Flinesoft/HandySwift#30]
I suggest to add the following extension to Comparable:

```
public extension Comparable {
    func bounded(lower: Self, upper: Self) -> Self {
        return min(upper, max(lower, self))
    }
}
```

**Usage**

```
let myInt = 5
let boundedInt = myInt.bounded(lower: 2, upper: 4)
print(boundedInt) // 4
```

**Motivation**

I often need to limit a value, and currently, I always use the min, max pattern also used within the `bounded(lower:upper:)` implementation. Using the new interface will make things fast to write and clear to understand, this is why I suggest to add it to HandySwift. As per the naming: We could also name it differently, e. g. `limited`.

**Comment by fredpi** [comment]
Another suggestion for the naming would be `clamp` to follow other languages.

**Comment by knothed** [comment]
@fredpi I would suggest `clamped` instead of `clamp`, as no in-place mutation is performed.
Therefore, `clamped(to:and:)` would be my recommendation.

**Comment by Dschee** [comment]
@fredpi Is there a related discussion about this in the Swift Forums? If not, did you consider suggesting the idea there, too? Would be great to get some feedback from the community before deciding for a naming.

In my experience the Swift community only decides to use an already introduced name from other languages for new features in Swift, if many developers have already gotten used to it. Since I never used `clamp` or `limit` before (or had the need for it) I don't think we should consider names from other languages too much, unless they already are great names. But neither `clamp` (or `clamped`) nor `limited` give me the feeling I could guess what it's doing – I would still need to look it up.

So what about something like `closest(in: Range)` or `Range.closest(to: Comparable)`? The usage would read naturally:

```swift
let dayOfTheMonth: Int = 31
// variant 1
let dayInFebruary: Int = dayOfTheMonth.closest(in: 0 ..< 28)
// variant 2
let dayInFebruary: Int = (0 ..< 28).closest(to: dayOfTheMonth)
```

What do you think?

**Comment by fredpi** [comment]
I just found out, that `Range` already offers a `clamped` interface for ranges:

```
extension Range {
  /// Returns a copy of this range clamped to the given limiting range.
  ///
  /// The bounds of the result are always limited to the bounds of `limits`.
  /// For example:
  ///
  ///     let x: Range = 0..<20
  ///     print(x.clamped(to: 10..<1000))
  ///     // Prints "10..<20"
  ///
  /// If the two ranges do not overlap, the result is an empty range within the
  /// bounds of `limits`.
  ///
  ///     let y: Range = 0..<5
  ///     print(y.clamped(to: 10..<1000))
  ///     // Prints "10..<10"
  ///
  /// - Parameter limits: The range to clamp the bounds of this range.
  /// - Returns: A new range clamped to the bounds of `limits`.
  @inlinable // trivial-implementation
  @inline(__always)
  public func clamped(to limits: Range) -> Range {
    let lower =         
      limits.lowerBound > self.lowerBound ? limits.lowerBound
          : limits.upperBound < self.lowerBound ? limits.upperBound
          : self.lowerBound
    let upper =
      limits.upperBound < self.upperBound ? limits.upperBound
          : limits.lowerBound > self.upperBound ? limits.lowerBound
          : self.upperBound
    return Range(uncheckedBounds: (lower: lower, upper: upper))
  }
}
```

Considering this interface is already available, introducing a similar feature for `Comparable` should probably follow the same naming, do you agree? Also, it should take a range as a parameter instead of explicit lower and upper bounds. We could also introduce a `mutating` variant:

```
public extension Comparable {
    /// If "self" is inside the given range, return it.
    /// Else, return either the lower or upper bound of the range,
    /// depending on if "self" is smaller or larger than the allowed value range.
    func clamped(to limits: Range<Self>) -> Self {
        return limits.lowerBound > self ? limits.lowerBound
            : limits.upperBound < self ? limits.upperBound
            : self
    }

    /// Clamp "self" so it is inside the given limits.
    mutating func clamp(to limits: Range<Self>) {
        self = clamped(to: limits)
    }
}
```

**Comment by fredpi** [comment]
I just browsed the Swift Forums, and it turns out this has been discussed before (suggesting `clamped` as a name). Here are some posts:

• https://forums.swift.org/t/applycap-and-applythreshold/15388/21
• https://forums.swift.org/t/revision-fixing-se-0177-add-clamp-to-to-the-stdlib/6219/2
• https://forums.swift.org/t/draft-add-clamped-to-to-the-stdlib/5442

**Comment by Dschee** [comment]
It makes sense to keep things consistent and name it `clamped(to: Range)` (and `clamp(to: Range)` for a mutating variant). Would happily review & merge a related PR. Good work regarding research! 👍
