### ISSUE TITLE
File headers don't match shared format

### ISSUE THREAD

**Issue by fredpi** [Flinesoft/HandySwift#31]
Some file headers match the old file header format, e. g.:

```
//
//  Unowned.swift
//  HandySwift
//
//  Created by Murat Yilmaz on 19.05.18.
//  Copyright © 2018 Flinesoft. All rights reserved.
//
```

instead of:

```
//
//  Created by Murat Yilmaz on 19.05.18.
//  Copyright © 2018 Flinesoft. All rights reserved.
//
```

Is this intentional, or should we adjust old headers to the new format?

**Comment by Dschee** [comment]
We've even gone further and now just use this:
```swift
//  Copyright © 2018 Flinesoft. All rights reserved.
```

There's no intention behind that, it's just a leftover. Feel free to fix! 💯

**Comment by fredpi** [comment]
Will create a PR soon ;)
