### ISSUE TITLE
Implement `average()` for more numeric types

### ISSUE THREAD

**Issue by knothed** [Flinesoft/HandySwift#36]
Currently, `func average() -> Double` is defined as an extension on `Collection where Element == Double`. What about `CGFloat`s?

I suggest to add a protocol `Field` (based on algebraic fields) providing addition, multiplication and division with `Self` elements, and also a `zero` and `one` element. This would allow both `average()` and `sum()` to be implemented more generically. `Double`, `Float` and `CGFloat` could conform to this protocol (with nearly no additional implementation effort).

The integer case would have to be treated specially though.

**Comment by Dschee** [comment]
CGFloats _are_ Doubles. It's just a typealias. Just command-click it and you'll be amazed. ;)

Please note that there are many libraries providing such mathematical extensions to Swift. HandySwift is only targeting to add the most common things that we think should be part of Swift in the first place. I don't think we should dive too much into such things and recommend other tools that are already amazing at such things instead.

If you really wanted to add such things, please consider searching through the Swift Forums for existing suggestions or pitching your idea there and discussing a bit before making a bigger pull request here. For now, I consider this a non-bug. I'll reopen if necessary.

**Comment by knothed** [comment]
I'm not quite sure what you mean by *`CGFloat`s are `Double`s*. I **know** that they are the same, at least on 64-bit systems, but that still doesn't allow me to provide a `CGFloat` as an argument to a function that has a `Double` as its parameter.

As a consequence, I cannot calculate the average of 2 `CGFloat`-values without first converting them to `Double` and then converting the result back to a `CGFloat`, resulting in code like this:

```
let averageXY = CGFloat([Double(view.frame.origin.x), Double(view.frame.origin.y)].average())
```

Also, I think you quite misunderstood my intent – I just wanted to generalize the `sum` and `average` methods to `CGFloats` and `Floats`. I do **not** want to provide any kind of mathematical extensions or further, more complex, mathematical stuff. :)

The natural consequence of generalising average calculation is a protocol providing the required basic arithmetic operations: addition and division. The implementation would be extremely minimal because all targeted Swift types already provide these functions.

**Comment by Dschee** [comment]
Ah yeah, sorry, I mixed things up with `TimeInterval`. Of course `CGFloat` is its own type. 😅 

Okay, I'll reopen this. Could you please just post a PR with the approach you mean? I think then the discussion about the details of the implementation will be much easier. Currently, I'm not entirely sure what your suggested approach is. A PR would make that very clear. :)

**Comment by knothed** [comment]
Yes, I'll drop a PR. Thank you very much for reconsidering :)
