### ISSUE TITLE
String isNilOrEmpty

### ISSUE THREAD

**Issue by knothed** [Flinesoft/HandySwift#37]
Sometimes, when dealing with viewModels with contain optional values, I find myself writing code like this:
```
if (viewModel.text ?? "").isEmpty { ... }
```
An equivalent alternative is this:
```
if viewModel.text?.count > 0 { ... }
```

Still, I think it is not as concise as it should be.

C# provides a method `String.IsNullOrEmpty`. What do you think about a respective Swift method? E.g. an extension to `Optional where Wrapped == StringProtocol` providing a property `isNilOrEmpty`?

Also, because HandySwift already provides an `isBlank` property, this could be extended to also provide a `isNilOrBlank` property, if this is a common use-case.

**Comment by Dschee** [comment]
Is there a related discussion on the Swift forums? What do they think about such a thing?

**Comment by knothed** [comment]
Good question, I will take a look later today.

I just came over the idea to introduce this extension not only to `String(Protocol)`, but to all `Collection`s – it may be equally useful for `Array`s, `Dictionary`s etc.

**Comment by Dschee** [comment]
Yeah, if implemented at all, it should be implemented at the level where `isEmpty` is defined.

Also note that I got inspired for the `isBlank` method by Ruby, which has a `blank?` method. There's also a `present?` method in Ruby which does exactly what you're asking for. So we may want to consider something like `isPresent` for naming then which I think reads more naturally than `isNilOrEmpty` where you have an `or` and thus have to think a little more until you understand it.

**Comment by knothed** [comment]
You're right, `isPresent` reads more fluently, but I don't think it's as clear, especially for non-Ruby users. My first intention would be that `isPresent` states if there is a non-nil value wrapped in an optional. Thus it could be easily misunderstood.

**Comment by Dschee** [comment]
But that's no misunderstanding, if it's true, that actually means that it's non-nil. Only in the Collection case it additionally means it's not empty, since something is present. 😁

**Comment by Dschee** [comment]
But it solves the same issue as your suggestion plus it needs no negation in guard statements.

**Comment by knothed** [comment]
True, you're right :D `isPresent` is good. I think `hasElement` would also sound nice, but this would more naturally be a property of Collection, not of Optional<Collection>, so maybe `isPresent` is best...

**Comment by knothed** [comment]
Well, maybe `hasElement` for `Collection` is not *that* bad, because it would allow code like this:
```
guard viewModel.text?.hasElement else { ... }
```

It is just a plain negation of `isEmpty`, but would work perfectly with optional chaining. :)

**Comment by Dschee** [comment]
Since `isPresent` can be applied to any Optional, I think it would be more useful as a name since the feature would be more useful in general.

**Comment by knothed** [comment]
How would you define `isPresent` if you would want to extend it to all Optionals?
It would definitely collide with the original intent (that collection.isPresent = non-nil and non-empty)

**Comment by Dschee** [comment]
Why? On collections we would simply override it. 😉

**Comment by knothed** [comment]
Hmm... it would be a bit confusing if it is a general non-nil operator, but behaves differently only on Collections 😁
The user would have to be explicitly informed about this.

**Comment by Dschee** [comment]
It's not a non-nil operator. It's an operator, that informs you about presence. For `Optional(Int)` presence is the existence of an `Int` value. For a collection "presence" means that it contains elements.

**Comment by knothed** [comment]
Well, I would argue that even an empty collection is `present` in the sense that it exists, in contrast to it being nil.

I think there is a potential for misunderstandings...

**Comment by knothed** [comment]
Is there a design rationale on why Ruby called it `present`? 😁

**Comment by Dschee** [comment]
There sure had been. No idea if it can be found anywhere. Please also note that we could first introduce `isBlank` for all collections instead of only for Strings. That would  replace the `isNilOrEmpty` with a naming we already introduced. Then, we can think of introducing the negative form via `isPresent`, too.

**Comment by knothed** [comment]
Yeah, sounds good. But this doesn't solve the problem yet, as `collection?.isEmpty` would actually return `false` for a `Optional<Collection>` which is nil.

Therefore, I think it does not suffice to just extend `isEmpty` to Collections, but it should also be added to `Optional<Collection>`, returning `true` when either the collection is nil or non-nil and empty.

**Comment by knothed** [comment]
This would allow me, coming back to the original example, to write:
```
if viewModel.text.isEmpty ...
```
, which would eliminate the chaining with `""`.

**Comment by knothed** [comment]
(Or `isBlank`, whatever fits better.)
