### ISSUE TITLE
Add Withable support for any NSObject by default

### ISSUE THREAD

**Issue by Jeehut** [Flinesoft/HandySwift#39]

**Comment by knothed** [comment]
Why specifically for any `NSObject`? And not for, for example, any `AnyObject` or `Any`? What is the need for `NSObjects` to be `Withable`?

**Comment by Jeehut** [comment]
@knothed Have you tried extending the protocols `AnyObject` or `Any` with `Withable`? At least I'm getting this error when trying this: "Non-nominal type 'Any' cannot be extended"

**Comment by knothed** [comment]
Of course, you're right, I forgot it's not possible to extend Any or AnyObject.
