### ISSUE TITLE
Switch covers known cases, but 'DispatchTimeInterval' may have additional unknown values, possibly added in future versions

### ISSUE THREAD

**Issue by nikhilpandey4** [Flinesoft/HandySwift#42]
Its giving a yellow warning that Switch covers known cases, but 'DispatchTimeInterval' may have additional unknown values, possibly added in future versions And asking to implement unknown default clause.

**Comment by Jeehut** [comment]
We're not seeing any warnings, are you sure you're on the latest version of HandySwift? I'm also asking because of https://github.com/Flinesoft/HandySwift/issues/41 where it's clear that you can't have the latest version. :)

**Comment by Jeehut** [comment]
Closing, see my comment [here](https://github.com/Flinesoft/HandySwift/issues/41#issuecomment-589798448).
