### ISSUE TITLE
Support Xcode 10.2 or Update CI

### ISSUE THREAD

**Issue by knothed** [Flinesoft/HandySwift#45]
I noticed that the CI emitted an error for the most recent commit on stable (cba3181864b130dd183addd198e38b5c636e595f) with the following cause:
![image](https://user-images.githubusercontent.com/18039001/75984694-2936bc80-5eeb-11ea-9d52-dc5464dd369f.png)

[Omitting the `return` statement for single-line functions](https://github.com/apple/swift-evolution/blob/master/proposals/0255-omit-return.md) is a feature since Swift 5.1. The CI is currently using Xcode 10.2.x (which is deprecated on bitrise anyway), which means a Swift version < 5.1.

This means, either the CI should be configured to use a more recent version of Xcode and Swift, or single-line return statements should use an explicit `return` to allow compatibility with Xcode 10.2.x.

**Comment by Jeehut** [comment]
CI was updated to the latest Xcode versions always from now on.
