### ISSUE TITLE
Support for Swift 2.3

### ISSUE THREAD

**Issue by dunqi** [Flinesoft/HandySwift#5]
Please support Swift 2.3

**Comment by Dschee** [comment]
Are you using HandySwift on a copy and paste basis? Cause it shouldn't make any difference if you have Xcode 8 installed when targeting frameworks – Xcode 8 will automatically pick up the correct version (between Swift 2.3 and Swift 3) and compile the whole thing accordingly.

Afaik you can have a Swift 3 compiled framework included in a Swift 2.3 project. But I'm not entirely sure – please report if that's not the case. We can create a separate branch for Swift 2.3 users if needed.

**Comment by Dschee** [comment]
There is now a new branch names "support/swift2.3" which you can use for Swift 2.3 support via Carthage. Note that b70ebf334bcc29efd21f556f7300f19603a10774 also updates the README with hints to Swift 2.2 and 2.3 compatibility for future reference.
