### ISSUE TITLE
Swift3 on CocoaPods?

### ISSUE THREAD

**Issue by nikhil-pagalguy** [Flinesoft/HandySwift#6]
I tried using pod "HandySwift", "~> 1.3". But did not work. Have you updated this version to cocoapods?

**Comment by Dschee** [comment]
Thank you for opening an issue on this. When I released version 1.3.0 there was an issue with CocoaPods without good explanations on the web on how to fix it (as it was new). The truth is that I don't like CocoaPods (for several reasons) so I didn't invest much time in uploading a new version after it didn't work immediately. I have made the experience that CocoaPods doesn't work with new Xcode versions very often and therefore always recommend using Carthage instead, which has its downsides (long build times), too, but at least works most of the time without issues.

Anyway, I understand the need for CocoaPods support and just tried again, updated to a new CocoaPods version, applied some suggestions to fix issues and it worked. It should now install fine with CocoaPods.

There was already problems with 1.2.0 by the way which were noted in #2 – I'm closing that one, too.
