### ISSUE TITLE
UIKIT define

### ISSUE THREAD

**Issue by raberm** [Flinesoft/HandySwift#7]
HandySwift sets `OTHER_SWIFT_FLAGS = "-D UIKIT";` on the project file, then checking with `#if UIKIT`.
This version might be easier to handle as it needs no flags (Cocoapods didn't set it up for me, fe)

`#if os(iOS) || os(tvOS)`

**Comment by Dschee** [comment]
You're absolutely right, that would be a better solution now, I simply forgot to update that part when migrating to newer Swift versions, where the if os(platform) was introduced. Good catch!

Would you mind implementing tha change yourself and sending in a pull request? I would gladly merge it and release a new version. :+1:

**Comment by Dschee** [comment]
Fixed via #8 – this issue should be solved in the next version update. Do you need one urgently – or, to ask differently, did you find a workaround for this issue? Otherwise I'd wait until other features are added / bugs are fixed and release then.
